name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install wasm-pack from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-pack

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json
      - working-directory: ./javascript
        run: |
          npm ci

      - name: Build
        working-directory: ./javascript
        run: npm run build-browser && npm run build-node
      
      - name: Run tests
        working-directory: ./javascript
        run: npm run test

      - name: Create release
        working-directory: ./javascript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          tar -czvf $tag.tar.gz ./
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${tag#v}" \
              --generate-notes \
              $tag.tar.gz
      - name: Publish to npmjs
        working-directory: ./javascript
        run: |
          echo -e "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN\nregistry=https://registry.npmjs.org/\nalways-auth=true" > .npmrc
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
